# Test against all supported versions of Node.js on windows
environment:
    matrix:
        - nodejs_version: '8'
        - nodejs_version: '9'
        - nodejs_version: '10'

cache:
    - node_modules
    - '%APPDATA%\npm-cache'

# Install scripts. (runs after repo cloning)
install:
    # Get the version of Node.js
    - ps: Install-Product node $env:nodejs_version
    - npm install --global npm@latest
    - npm ci

# Post-install test scripts.
test_script:
    # Output useful info for debugging.
    - node --version
    - npm --version
    # run tests
    - npm test

# Don't actually build.
build: off
