language: node_js

# Test linux and osx
os:
    - linux
    - osx

# Test against all supported versions of Node.js
node_js:
    - '8'
    - '9'
    - '10'
    - '11'

# Run ESLint after npm test
script:
    - npm run eslint

cache:
    directories:
        - 'node_modules'
